version: "3.5"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - "8085:80"
    links:
      - fpm
    volumes:
      - ./src:/var/www/newpro    #./
    networks:
      - newpro
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    #entrypoint: sh /bin/run.sh
    volumes:
#      - ./:/var/www/newpro
      - ./src:/var/www/newpro         #./
      - ./scripts/phpEntry.sh:/bin/run.sh
    ports:
      - "9000:9000"
#    env_file:
#      - '.env'
    depends_on:
      - mysql
    networks:
      - newpro
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: newpro
      MYSQL_ROOT_PASSWORD: 1111
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - newpro
#  cron:
#    build:
#      context: .
#      dockerfile: docker/Cron.Dockerfile
#    container_name: cron
#    volumes:
#      - ./:/var/www/newpro
#    networks:
#      - newpro
#Volumes
volumes:
  mysqldata:
    driver: local

networks:
  newpro: