CREATE DATABASE IF NOT EXISTS newpro;
CREATE DATABASE IF NOT EXISTS kyxhi CHARACTER SET latin1 COLLATE latin1_general_ci;

CREATE USER IF NOT EXISTS 'newpro'@'%' IDENTIFIED BY '1111';

GRANT ALL PRIVILEGES ON newpro.* TO 'newpro'@'%';
GRANT ALL PRIVILEGES ON kyxhi.* TO 'newpro'@'%';

FLUSH PRIVILEGES;